name: DevSecOps Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  security-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        run: |
          echo "Verificando arquivos..."
          ls src/ || echo "Diretório src/ não encontrado!"
          echo "Build OK!"

      - name: Gitleaks Scan
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Semgrep
        run: pip3 install semgrep

      - name: Run Semgrep
        run: |
          semgrep scan \
            --config=auto \
            --severity=ERROR \
            --error \
            src/

            

      - name: Install Syft
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b ./bin

      - name: Generate SBOM
        run: |
          ./bin/syft dir:. -o cyclonedx-json > sbom.json



      - name: Install Grype
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b ./bin

      - name: Run Grype
        run: |
          ./bin/grype dir:. --fail-on medium

          

      - name: Generate GitHub Pages Content
        run: |
          mkdir -p docs
          cp README.md docs/README
      

      - name: Deploy to GitHub Pages
        run: |
          touch docs/.nojekyll

          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          git add docs/
          git commit -m "Update GitHub Pages report" || echo "Nenhuma alteração para commitar"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}